# Generated by Django 5.1.7 on 2025-04-29 15:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alunos',
            fields=[
                ('matricula', models.AutoField(default=2, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=70, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('data_nascimento', models.DateField(verbose_name='Data de nascimento')),
                ('status', models.BooleanField(default=True, verbose_name='Ativo')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Aluno',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Coordenador',
            fields=[
                ('matricula', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=70, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('data_nascimento', models.DateField(verbose_name='Data de nascimento')),
                ('senha', models.CharField(max_length=128, verbose_name='Senha')),
                ('segmento', models.IntegerField(verbose_name='Segmento')),
                ('status', models.BooleanField(default=True, verbose_name='Ativo')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Atualizado em')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('matricula', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=70, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('data_nascimento', models.DateField(verbose_name='Data de nascimento')),
                ('senha', models.CharField(max_length=128, verbose_name='Senha')),
                ('segmento', models.IntegerField(verbose_name='Segmento')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
        ),
    ]
