# Generated by Django 5.1.7 on 2025-04-29 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunos',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='alunos',
            name='matricula',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
