# Generated by Django 5.1.7 on 2025-04-29 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_alunos_create_at_alter_alunos_matricula'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alunos',
            old_name='updated_at',
            new_name='update_at',
        ),
    ]
