# Generated by Django 5.1.7 on 2025-04-30 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0003_alter_falta_aluno_alter_falta_disciplina_and_more'),
        ('usuarios', '0004_aluno'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alunos',
        ),
        migrations.AlterModelOptions(
            name='coordenador',
            options={'ordering': ['nome', 'segmento'], 'verbose_name': 'Coordenador', 'verbose_name_plural': 'Coordenadores'},
        ),
        migrations.AlterModelOptions(
            name='professor',
            options={'ordering': ['nome', 'segmento'], 'verbose_name': 'Professor', 'verbose_name_plural': 'Professores'},
        ),
        migrations.AlterField(
            model_name='coordenador',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='coordenador',
            name='segmento',
            field=models.IntegerField(choices=[(1, 'Educação Infantil'), (2, 'Ensino Fundamental'), (0, 'Sem segmento')], default=0),
        ),
        migrations.AlterField(
            model_name='professor',
            name='segmento',
            field=models.IntegerField(choices=[(1, 'Educação Infantil'), (2, 'Ensino Fundamental'), (0, 'Sem segmento')], default=0),
        ),
        migrations.AlterField(
            model_name='professor',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='alunos', to='turmas.turma'),
        ),
    ]
