# Generated by Django 5.1.7 on 2025-05-04 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0006_alter_falta_aluno_alter_falta_disciplina_and_more'),
        ('usuarios', '0005_delete_alunos_alter_coordenador_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordenador',
            name='turma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='coordenador_turma', to='turmas.turma', verbose_name='Turma'),
        ),
        migrations.AddField(
            model_name='professor',
            name='turma_disciplina',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='professor_turma_disciplina', to='turmas.turma_disciplina', verbose_name='Turma e Disciplina'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='turma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='alunos', to='turmas.turma'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='segmento',
            field=models.IntegerField(choices=[(1, 'Educação Infantil'), (2, 'Ensino Fundamental'), (0, 'Sem segmento')], default=0, verbose_name='Segmento'),
        ),
    ]
