# Generated by Django 5.1.7 on 2025-05-27 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0008_remove_falta_disciplina_falta_turma_disciplina'),
        ('usuarios', '0006_coordenador_turma_professor_turma_disciplina_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='turma_disciplina',
        ),
        migrations.AddField(
            model_name='professor',
            name='turma_disciplina',
            field=models.ManyToManyField(null=True, related_name='professor_turma_disciplina', to='turmas.turma_disciplina', verbose_name='Turma e Disciplina'),
        ),
    ]
