# Generated by Django 5.1.7 on 2025-05-27 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0008_remove_falta_disciplina_falta_turma_disciplina'),
        ('usuarios', '0007_remove_professor_turma_disciplina_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='turma_disciplina',
        ),
        migrations.AddField(
            model_name='professor',
            name='turma_disciplina',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='professor_turma_disciplina', to='turmas.turma_disciplina', verbose_name='Turma e Disciplina'),
        ),
    ]
