# Generated by Django 5.1.7 on 2025-05-27 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_remove_professor_turma_disciplina_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordenador',
            name='email',
            field=models.CharField(default='fulano@gmail.com', max_length=120, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='professor',
            name='email',
            field=models.CharField(default='fulano@gmail.com', max_length=120, verbose_name='E-mail'),
        ),
    ]
