# Generated by Django 5.1.7 on 2025-05-28 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_coordenador_email_professor_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='senha',
            field=models.CharField(default='aluno123', max_length=128, verbose_name='Senha'),
        ),
    ]
