# Generated by Django 5.1.7 on 2025-06-08 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_aluno_user_coordenador_user_professor_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='turma_disciplina',
        ),
    ]
