# Generated by Django 5.1.7 on 2025-06-08 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0009_turma_disciplina_professor'),
        ('usuarios', '0012_remove_professor_turma_disciplina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='alunos', to='turmas.turma'),
        ),
    ]
