# Generated by Django 5.1.7 on 2025-05-04 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0005_delete_alunos_alter_coordenador_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avalicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('arquivo', models.FileField(upload_to='avaliacoes/', verbose_name='Arquivo')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('status', models.IntegerField(choices=[(1, 'Aplicada'), (2, 'Não Aplicada'), (3, 'Corrigida')], default=2, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontuacao', models.FloatField(verbose_name='Pontuação')),
                ('relevancia', models.IntegerField(choices=[(1, 'Alta'), (2, 'Media'), (3, 'Baixa'), (0, 'Sem relevância')], default=0, verbose_name='Relevância')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nota_aluno', to='usuarios.aluno')),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='nota_avaliacao', to='avaliacao.avalicao')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
                'ordering': ['pontuacao'],
            },
        ),
    ]
