# Generated by Django 5.1.7 on 2025-05-04 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Avalicao',
            new_name='Avaliacao',
        ),
    ]
