# Generated by Django 4.2.7 on 2025-06-05 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0003_avaliacao_turma_disciplina_alter_nota_avaliacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='data_aplicacao',
            field=models.DateField(null=True, verbose_name='Data'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='periodo_letivo',
            field=models.IntegerField(choices=[(0, 'Selecione um período'), (1, 'Primeiro semestre'), (2, 'Segundo semestre')], default=0, verbose_name='Período'),
        ),
    ]
