# Generated by Django 5.1.7 on 2025-06-10 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0004_avaliacao_data_aplicacao_avaliacao_periodo_letivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='relevancia',
            field=models.IntegerField(choices=[(1, 'Alta'), (2, 'Media'), (3, 'Baixa'), (0, 'Sem relevância')], default=0, null=True, verbose_name='Relevância'),
        ),
    ]
