# Generated by Django 5.1.7 on 2025-04-30 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disciplina',
            options={'ordering': ['nome'], 'verbose_name': 'Turma Disciplina', 'verbose_name_plural': 'Turma Disciplinas'},
        ),
        migrations.AlterModelOptions(
            name='falta',
            options={'verbose_name_plural': 'Faltas'},
        ),
        migrations.AlterModelOptions(
            name='turma',
            options={'verbose_name_plural': 'Turmas'},
        ),
        migrations.RenameField(
            model_name='turma',
            old_name='quantidadeMax',
            new_name='quantidade_maxima',
        ),
        migrations.RemoveField(
            model_name='turma',
            name='alunos',
        ),
    ]
