# Generated by Django 5.1.7 on 2025-04-30 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0002_alter_disciplina_options_alter_falta_options_and_more'),
        ('usuarios', '0004_aluno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='falta',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='usuarios.aluno'),
        ),
        migrations.AlterField(
            model_name='falta',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='faltas', to='turmas.disciplina'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Ativa'),
        ),
        migrations.AlterField(
            model_name='turma_disciplina',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='turmas', to='turmas.disciplina'),
        ),
        migrations.AlterField(
            model_name='turma_disciplina',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='turma', to='turmas.turma'),
        ),
    ]
