# Generated by Django 5.1.7 on 2025-04-30 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0003_alter_falta_aluno_alter_falta_disciplina_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disciplina',
            options={'ordering': ['nome'], 'verbose_name': 'Disciplina', 'verbose_name_plural': 'Disciplinas'},
        ),
        migrations.AlterModelOptions(
            name='turma_disciplina',
            options={'ordering': ['turma'], 'verbose_name': 'Turma Disciplina', 'verbose_name_plural': 'Turmas Disciplinas'},
        ),
    ]
