# Generated by Django 5.1.7 on 2025-05-04 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0004_alter_disciplina_options_and_more'),
        ('usuarios', '0005_delete_alunos_alter_coordenador_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='falta',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='falta_aluno', to='usuarios.aluno'),
        ),
        migrations.AlterField(
            model_name='turma_disciplina',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='disciplina_turma', to='turmas.disciplina'),
        ),
        migrations.AlterField(
            model_name='turma_disciplina',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='turma_disciplina', to='turmas.turma'),
        ),
    ]
