# Generated by Django 5.1.7 on 2025-05-04 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0005_alter_falta_aluno_alter_turma_disciplina_disciplina_and_more'),
        ('usuarios', '0005_delete_alunos_alter_coordenador_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='falta',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='falta_aluno', to='usuarios.aluno'),
        ),
        migrations.AlterField(
            model_name='falta',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faltas', to='turmas.disciplina'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='numero',
            field=models.CharField(max_length=3, verbose_name='Numero'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='sala',
            field=models.CharField(max_length=3, verbose_name='Numero da sala'),
        ),
    ]
