# Generated by Django 5.1.7 on 2025-05-20 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0007_alter_turma_quantidade_maxima'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='falta',
            name='disciplina',
        ),
        migrations.AddField(
            model_name='falta',
            name='turma_disciplina',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='faltas', to='turmas.turma_disciplina'),
        ),
    ]
