# Generated by Django 5.1.7 on 2025-06-08 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0008_remove_falta_disciplina_falta_turma_disciplina'),
        ('usuarios', '0012_remove_professor_turma_disciplina'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma_disciplina',
            name='professor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='usuarios.professor', verbose_name='Professor'),
        ),
    ]
