# Generated by Django 5.1.7 on 2025-06-08 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0009_turma_disciplina_professor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='falta',
            name='data',
            field=models.DateField(auto_now_add=True, verbose_name='Data'),
        ),
    ]
