# Generated by Django 5.1.7 on 2025-06-10 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0010_alter_falta_data'),
        ('usuarios', '0013_alter_aluno_turma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='falta',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Falta'),
        ),
        migrations.AlterField(
            model_name='turma_disciplina',
            name='professor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='prof_turma_disciplina', to='usuarios.professor', verbose_name='Professor'),
        ),
    ]
